### ISSUE TITLE
Store ID is hard-coded in HTML

### ISSUE THREAD

**Issue by makfruit** [hans2103/mod_ecwid_product#1]
Hi!

The store ID setting seems to be not used in the output HTML/Javascript code that the module generates - it contains '1322147' as hard-coded store ID. That is why the Add to bag  widget doesn't work (it works only for the store 1322147). Here is the code from 'defaut.php':

<script type="text/javascript" src="http://app.ecwid.com/script.js?1322147" charset="utf-8"></script>

Here, the store ID should be replaced with user-defined store ID.

**Comment by hans2103** [comment]
oops... my bad... solved
case closed
